language: python
python:
# - "2.6"
  - "2.7"
# - "3.2"
# - "3.3"
# - "3.4"
# - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "python setup.py install"
# command to run tests
script:
  - nosetests --with-coverage --cover-package=ene_irc
after_success: coveralls