"""initial migrations

Revision ID: 510ed749a76e
Revises: 
Create Date: 2015-10-29 00:39:39.705729

"""

# revision identifiers, used by Alembic.
revision = '510ed749a76e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
